"""add phone_public to users

Revision ID: 06c50c9891d9
Revises: b909f2e991f9
Create Date: 2026-06-24 21:10:42.609675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c50c9891d9'
down_revision: Union[str, None] = 'b909f2e991f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_public')
    # ### end Alembic commands ###
