"""add governorate and coordinates to properties

Revision ID: 855f5c321ada
Revises: e45514f6caab
Create Date: 2026-06-25 15:32:01.362281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855f5c321ada'
down_revision: Union[str, None] = 'e45514f6caab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('governorate', sa.String(length=40), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'governorate')
    # ### end Alembic commands ###
