"""add account type and company fields to users

Revision ID: b909f2e991f9
Revises: 1eefebdcb71d
Create Date: 2026-06-24 16:54:07.824319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b909f2e991f9'
down_revision: Union[str, None] = '1eefebdcb71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_user_id', sa.UUID(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_user_id', name='uq_follow_follower_followed')
    )
    op.create_index('ix_follows_followed_follower', 'follows', ['followed_user_id', 'follower_id'], unique=False)
    op.create_index(op.f('ix_follows_followed_user_id'), 'follows', ['followed_user_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.add_column('properties', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_properties_published_at'), 'properties', ['published_at'], unique=False)
    op.add_column('users', sa.Column('account_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('company_about', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('company_website', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('company_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # verification_status must be NOT NULL, but the table already has rows —
    # add nullable, backfill, then tighten, rather than failing on ALTER.
    op.add_column('users', sa.Column('verification_status', sa.String(length=20), nullable=True))
    op.execute("UPDATE users SET verification_status = 'unverified' WHERE verification_status IS NULL")
    op.alter_column('users', 'verification_status', nullable=False)

    # Backfill existing active listings so they don't all look "new" the
    # moment the follow-digest feature reads published_at.
    op.execute("UPDATE properties SET published_at = created_at WHERE status = 'active'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'company_address')
    op.drop_column('users', 'company_website')
    op.drop_column('users', 'company_about')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'account_type')
    op.drop_index(op.f('ix_properties_published_at'), table_name='properties')
    op.drop_column('properties', 'published_at')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followed_user_id'), table_name='follows')
    op.drop_index('ix_follows_followed_follower', table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
