"""Add listing verification + verification_documents

Revision ID: bfd3349c4a88
Revises: 855f5c321ada
Create Date: 2026-06-26 00:31:05.122948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd3349c4a88'
down_revision: Union[str, None] = '855f5c321ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_documents_property_id'), 'verification_documents', ['property_id'], unique=False)
    op.create_index(op.f('ix_verification_documents_user_id'), 'verification_documents', ['user_id'], unique=False)
    op.add_column('properties', sa.Column('verification_status', sa.String(length=20), server_default='unverified', nullable=False))
    op.add_column('properties', sa.Column('verification_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('verification_rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'verification_rejection_reason')
    op.drop_column('properties', 'verification_reviewed_at')
    op.drop_column('properties', 'verification_status')
    op.drop_index(op.f('ix_verification_documents_user_id'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_property_id'), table_name='verification_documents')
    op.drop_table('verification_documents')
    # ### end Alembic commands ###
