"""add last_notification_at to conversations

Revision ID: d062f68588b9
Revises: d2f79036c67c
Create Date: 2026-05-23 20:37:36.446535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd062f68588b9'
down_revision: Union[str, None] = 'd2f79036c67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_notification_at')
    # ### end Alembic commands ###
