import uuid
from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Integer, func
from sqlalchemy.dialects.postgresql import UUID

from app.database import Base


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Optional — anonymous users can chat in v1.0
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Groups messages into a conversation. Generated by the frontend per chat session.
    conversation_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # 'user' or 'assistant' (matches Ollama/OpenAI convention)
    role = Column(String(20), nullable=False)

    content = Column(Text, nullable=False)
    locale = Column(String(5), nullable=False, default="en")

    # For assistant messages: model name + token counts + latency
    model = Column(String(100), nullable=True)
    prompt_tokens = Column(Integer, nullable=True)
    completion_tokens = Column(Integer, nullable=True)
    latency_ms = Column(Integer, nullable=True)

    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    def __repr__(self) -> str:
        return f"<ChatMessage role={self.role} user={self.user_id}>"
